import "lib/std";

fun willFail() > num !> str {
    throw "i'm failing";
    return 1;
}

test "Inline catch clauses" {
    assert((willFail() catch 0) == 0, message: "error or default value");
}